resources:
  - name: app-repo
    type: git
    source:
      uri: https://github.com/wtoxy/order-eats.git
      branch: master

  - name: docker-image
    type: docker-image
    source:
      repository: lilram/order-eats
      username: ((docker-username))
      password: ((docker-token))

jobs:
  - name: build-docker-image
    plan:
      - get: docker-image
        trigger: true
      - get: app-repo
        trigger: true
      - task: build-docker
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: docker, tag: 'latest'}
          inputs:
            - name: app-repo
          params:
            DOCKER_USERNAME: ((docker-username))
            DOCKER_TOKEN: ((docker-token))
            IMAGE_NAME: lilram/order-eats
          run:
            path: sh
            args:
              - -exc
              - |
                cd app-repo
                echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
                docker build -t $IMAGE_NAME .
                docker push $IMAGE_NAME


